<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 *
 * @link https://www.adminer.org/plugins/#use
 */

// Support the plugin "Designs".

// Don't allow all designs, only the most common ones.
$designsPreselected = [
    'brade',
    'bueltge',
    'esterka',
    'flat',
    'haeckel',
    'hever',
    'konya',
    'lucas-sandery',
    'nette',
    'ng9',
    'pappu687',
    'pokorni',
    'price',
    'rmsoft',
];
$designs = [];
// Relative to the Omeka admin route.
$baseUrl = '../modules/Adminer/asset/vendor/adminer/designs';
foreach (glob(dirname(__DIR__, 4) . '/asset/vendor/adminer/designs/**/*.css') as $filename) {
    $name = basename(dirname($filename));
    if (!in_array($name, $designsPreselected)) {
        continue;
    }
    $basename = basename($filename);
    $designs["$baseUrl/$name/$basename"] = $name;
}

// Load only wanted files for the used plugins below.
$list = [
    // Specify enabled plugins here.
    'dark-switcher',
    'designs',
    // 'dump-alter',
    // 'dump-json',
    // 'dump-xml',
    // 'dump-zip',
    // 'edit-textarea',
    'foreign-system',
    // 'frames',
    // 'json-column',
    'pretty-json-column',
    'table-structure',
    'tables-filter',
    // 'version-noverify',

    // Not default plugins.
    // 'disable-tables',
    // 'folder-import',
    // 'search-autocomplete',
    // 'sticky-columns',
    // 'tree-view',

    // Automatically loaded.
    // 'omeka',
];

// Specific plugins.
require_once dirname(__DIR__, 4) . '/src/AdminerOmeka.php';
require_once dirname(__DIR__, 4) . '/src/AdminerCleanUrls.php';

// foreach (glob(dirname(__DIR__, 4) . '/asset/vendor/adminer/adminer-plugins/*.php') as $filename) {
$baseDir = dirname(__DIR__, 4) . '/asset/vendor/adminer/adminer-plugins';
foreach ($list as $filename) {
    require_once "$baseDir/$filename.php";
}

return [
    // The omeka plugin manages auto-login, display of current database only and
    // default css.
    new AdminerOmeka($designs),
    new AdminerCleanUrls(['login']),

    // Specify enabled plugins here.
    new AdminerDarkSwitcher(),
    new AdminerDesigns($designs),
    // new AdminerDumpAlter(),
    // new AdminerDumpJson(),
    // new AdminerDumpXml(),
    // new AdminerDumpZip(),
    // new AdminerEditTextarea(),
    new AdminerForeignSystem(),
    // new AdminerFrames(),
    // new AdminerJsonColumn(),
    new AdminerPrettyJsonColumn(),
    new AdminerTableStructure(),
    new AdminerTablesFilter(),
    // new AdminerVersionNoverify(),

    // Not default plugins.
    // new AdminerDisableTables(),
    // new AdminerFolderImport(),
    // new AdminerSearchAutocomplete(),
    // new AdminerStickyColumns(),
    // new AdminerTreeView(),
];
