<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 *
 * @link https://www.adminer.org/plugins/#use
 * This is an adaptation of /vendor/vrana/adminer/plugins/plugin.php.
 */

// Support the plugin "Designs".
function listDesigns()
{
    static $designs;
    if (is_null($designs)) {
        $designs = [];
        foreach (glob(dirname(__DIR__, 4) . '/vendor/vrana/adminer/designs/**/*.css') as $filename) {
            $name = basename(dirname($filename));
            // Relative to the Omeka admin route.
            $designs['../modules/Adminer/vendor/vrana/adminer/designs/' . $name . '/' . basename($filename)] = $name;
        }
    }
    return $designs;
}

function adminer_object() {
    include_once dirname(__DIR__, 4) . '/vendor/vrana/adminer/plugins/plugin.php';
    foreach (glob(dirname(__DIR__, 4) . '/asset/vendor/adminer/plugins/*.php') as $filename) {
        include_once $filename;
    }

    $plugins = [
        // Specify enabled plugins here.
        new AdminerDatabaseHide(['information_schema']),
        new AdminerDumpJson,
        new AdminerDumpBz2,
        new AdminerDumpZip,
        new AdminerDumpXml,
        new AdminerDumpAlter,
        //~ new AdminerSqlLog("past-" . rtrim(`git describe --tags --abbrev=0`) . ".sql"),
        //~ new AdminerEditCalendar(script_src("../externals/jquery-ui/jquery-1.4.4.js") . script_src("../externals/jquery-ui/ui/jquery.ui.core.js") . script_src("../externals/jquery-ui/ui/jquery.ui.widget.js") . script_src("../externals/jquery-ui/ui/jquery.ui.datepicker.js") . script_src("../externals/jquery-ui/ui/jquery.ui.mouse.js") . script_src("../externals/jquery-ui/ui/jquery.ui.slider.js") . script_src("../externals/jquery-timepicker/jquery-ui-timepicker-addon.js") . "<link rel='stylesheet' href='../externals/jquery-ui/themes/base/jquery.ui.all.css'>\n<style>\n.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }\n.ui-timepicker-div dl { text-align: left; }\n.ui-timepicker-div dl dt { height: 25px; }\n.ui-timepicker-div dl dd { margin: -25px 0 10px 65px; }\n.ui-timepicker-div td { font-size: 90%; }\n</style>\n", "../externals/jquery-ui/ui/i18n/jquery.ui.datepicker-%s.js"),
        //~ new AdminerTinymce("../externals/tinymce/jscripts/tiny_mce/tiny_mce_dev.js"),
        //~ new AdminerWymeditor(array("../externals/wymeditor/src/jquery/jquery.js", "../externals/wymeditor/src/wymeditor/jquery.wymeditor.js", "../externals/wymeditor/src/wymeditor/jquery.wymeditor.explorer.js", "../externals/wymeditor/src/wymeditor/jquery.wymeditor.mozilla.js", "../externals/wymeditor/src/wymeditor/jquery.wymeditor.opera.js", "../externals/wymeditor/src/wymeditor/jquery.wymeditor.safari.js")),
        new AdminerFileUpload(''),
        new AdminerJsonColumn,
        new AdminerSlugify,
        new AdminerTranslation,
        new AdminerForeignSystem,
        new AdminerEnumOption,
        new AdminerTablesFilter,
        new AdminerEditForeign,
        // Not default plugins.
        new AdminerDesigns(listDesigns()),
        // new AdminerDisableTables,
        // new AdminerEditTextarea,
        // new AdminerFolderImport,
        // new AdminerJsonColumn,
        // new AdminerPrettyJsonColumn,
        // new AdminerSearchAutocomplete,
        // new AdminerStickyColumns,
        new AdminerVersionNoverify
    ];

    class AdminerCustomization extends AdminerPlugin {
         function css()
         {
             $return = [];
             if (array_key_exists($_SESSION['design'], listDesigns())) {
                 $return[] = $_SESSION['design'];
                 return $return;
             }

             $filename = dirname(__DIR__, 4) . '/asset/vendor/adminer/adminer.css';
             if (file_exists($filename)) {
                 // Relative to the Omeka admin route.
                 $return[] = "../modules/Adminer/asset/vendor/adminer/adminer.css?v=" . crc32(file_get_contents($filename));
             }
             return $return;
         }
     }
     return new AdminerCustomization($plugins);
}
