<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var bool $hasDependencies
 * @var bool $hasReadOnly
 * @var bool $hasFullAccess
 * @var bool $hasFakeReadOnly
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->appendStylesheet($assetUrl('css/adminer.css', 'Adminer'));

$this->htmlElement('body')->appendAttribute('class', 'adminer');
?>

<?= $this->pageTitle($translate('Database manager'), 1, $translate('Adminer')) ?>

<strong><?= $escape($translate('WARNING')) ?></strong>
<p><?= $escape($translate('Use it at your own risk.')) ?></p>
<p><?= $escape($translate('It is highly recommended to use a read-only user to access database, because it’s very easy to break a database, even for people who know the Omeka code and all the modules perfectly.')) ?></p>
<p><?= $escape($translate('In all cases, it’s always recommended to backup your files and your databases automatically and before risky and non-risky commands, and to check your archives regularly, so you can roll back if needed.')) ?></p>
<p><?= $escape($translate('To edit an element, use the key <control> + click.')) ?></p>
<?php if ($hasDependencies): ?>
<p>
    <?php
    if ($hasReadOnly && !$hasFakeReadOnly) {
        echo $hyperlink($translate('Read-only access'), $url('admin/adminer-mysql', [], ['query' => ['login' => 'readonly']]), ['target' => '_blank']);
        echo '<br/>';
        echo $hyperlink($translate('Read-only access (interface for editor)'), $url('admin/adminer-editor-mysql', [], ['query' => ['login' => 'readonly']]), ['target' => '_blank']);
        echo '<br/>';
    }
    if ($hasFullAccess) {
        echo $hyperlink($translate('Full access'), $url('admin/adminer-mysql', [], ['query' => ['login' => 'full']]), ['target' => '_blank']);
        echo '<br/>';
        echo $hyperlink($translate('Full access (interface for editor)'), $url('admin/adminer-editor-mysql', [], ['query' => ['login' => 'full']]), ['target' => '_blank']);
    }
    ?>
</p>
<?php endif; ?>
